// goliday v1 API —— 节假日查询 gRPC 接口定义。
//
// 语义与 HTTP API 一致（见 docs/API.md）：
//   - 日期一律为 "YYYY-MM-DD" 字符串；
//   - 单日查询 detailed 切换粗/细粒度；多日明细 days 恒为细粒度数值；
//   - 区间为左闭右开 [start, end)，跨度上限 366 天；
//   - 离散列表自动去重并升序，与区间同时提供时取并集（mode=list）；
//   - 细粒度统计对组合日按标志位交叉计数（各键之和可大于 total_days）。
//
// 再生成（需 protoc 与两个插件在 PATH，在仓库根执行）：
//   protoc --go_out=. --go_opt=module=github.com/JayceChant/goliday \
//         --go-grpc_out=. --go-grpc_opt=module=github.com/JayceChant/goliday \
//         proto/goliday/v1/goliday.proto
// 参考版本：protoc v29.3、protoc-gen-go v1.36.5、protoc-gen-go-grpc v1.5.1。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: proto/goliday/v1/goliday.proto

package golidayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DayType 为位掩码（proto3 enum 无法表达位组合，以 uint32 表达，附取值注释）。
//
// 细粒度位：
//
//	1  ORDINARY   普通工作日
//	2  COMPENSATE 补班（归工作日段）
//	4  WEEKEND    周末（归节假日段）
//	8  FESTIVAL   节日（归节假日段）
//	16 ADJUSTED   调休（归节假日段）
//
// 粗粒度段值：
//
//	3  WORKDAY  = ORDINARY|COMPENSATE 工作日
//	28 HOLIDAY  = WEEKEND|FESTIVAL|ADJUSTED 节假日
//
// 细粒度合法组合全集：1 / 4 / 6 / 12 / 16 / 24（如 6=补班逢周末、24=节日当天调休）。
// 与核心包 goliday.DayType 完全一致。
type Day struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`                            // YYYY-MM-DD
	Type          uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                           // DayType 掩码数值
	TypeLabel     string                 `protobuf:"bytes,3,opt,name=type_label,json=typeLabel,proto3" json:"type_label,omitempty"` // 可读标签，如 "workday"、"festival|adjusted"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Day) Reset() {
	*x = Day{}
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Day) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Day) ProtoMessage() {}

func (x *Day) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Day.ProtoReflect.Descriptor instead.
func (*Day) Descriptor() ([]byte, []int) {
	return file_proto_goliday_v1_goliday_proto_rawDescGZIP(), []int{0}
}

func (x *Day) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Day) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Day) GetTypeLabel() string {
	if x != nil {
		return x.TypeLabel
	}
	return ""
}

// 统计结果。workday/holiday 恒填充（粗粒度）；
// ordinary/compensate/weekend/festival/adjusted 仅 detailed=true 时填充（细粒度交叉计数）。
type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workday       int32                  `protobuf:"varint,1,opt,name=workday,proto3" json:"workday,omitempty"`
	Holiday       int32                  `protobuf:"varint,2,opt,name=holiday,proto3" json:"holiday,omitempty"`
	Ordinary      int32                  `protobuf:"varint,3,opt,name=ordinary,proto3" json:"ordinary,omitempty"`
	Compensate    int32                  `protobuf:"varint,4,opt,name=compensate,proto3" json:"compensate,omitempty"`
	Weekend       int32                  `protobuf:"varint,5,opt,name=weekend,proto3" json:"weekend,omitempty"`
	Festival      int32                  `protobuf:"varint,6,opt,name=festival,proto3" json:"festival,omitempty"`
	Adjusted      int32                  `protobuf:"varint,7,opt,name=adjusted,proto3" json:"adjusted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_goliday_v1_goliday_proto_rawDescGZIP(), []int{1}
}

func (x *Stats) GetWorkday() int32 {
	if x != nil {
		return x.Workday
	}
	return 0
}

func (x *Stats) GetHoliday() int32 {
	if x != nil {
		return x.Holiday
	}
	return 0
}

func (x *Stats) GetOrdinary() int32 {
	if x != nil {
		return x.Ordinary
	}
	return 0
}

func (x *Stats) GetCompensate() int32 {
	if x != nil {
		return x.Compensate
	}
	return 0
}

func (x *Stats) GetWeekend() int32 {
	if x != nil {
		return x.Weekend
	}
	return 0
}

func (x *Stats) GetFestival() int32 {
	if x != nil {
		return x.Festival
	}
	return 0
}

func (x *Stats) GetAdjusted() int32 {
	if x != nil {
		return x.Adjusted
	}
	return 0
}

// 单日查询，对应 HTTP GET /api/v1/days?date=...
type GetDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`          // YYYY-MM-DD，必填
	Detailed      bool                   `protobuf:"varint,2,opt,name=detailed,proto3" json:"detailed,omitempty"` // 默认 false（粗粒度）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDayRequest) Reset() {
	*x = GetDayRequest{}
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDayRequest) ProtoMessage() {}

func (x *GetDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDayRequest.ProtoReflect.Descriptor instead.
func (*GetDayRequest) Descriptor() ([]byte, []int) {
	return file_proto_goliday_v1_goliday_proto_rawDescGZIP(), []int{2}
}

func (x *GetDayRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetDayRequest) GetDetailed() bool {
	if x != nil {
		return x.Detailed
	}
	return false
}

type GetDayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Type          uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` // detailed=false 为粗粒度值（3/28），true 为细粒度掩码
	TypeLabel     string                 `protobuf:"bytes,3,opt,name=type_label,json=typeLabel,proto3" json:"type_label,omitempty"`
	TotalDays     int32                  `protobuf:"varint,4,opt,name=total_days,json=totalDays,proto3" json:"total_days,omitempty"` // 恒为 1
	Stats         *Stats                 `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDayResponse) Reset() {
	*x = GetDayResponse{}
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDayResponse) ProtoMessage() {}

func (x *GetDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDayResponse.ProtoReflect.Descriptor instead.
func (*GetDayResponse) Descriptor() ([]byte, []int) {
	return file_proto_goliday_v1_goliday_proto_rawDescGZIP(), []int{3}
}

func (x *GetDayResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetDayResponse) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetDayResponse) GetTypeLabel() string {
	if x != nil {
		return x.TypeLabel
	}
	return ""
}

func (x *GetDayResponse) GetTotalDays() int32 {
	if x != nil {
		return x.TotalDays
	}
	return 0
}

func (x *GetDayResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// 区间/离散/混合查询，对应 HTTP GET /api/v1/days?start=...&end=...&dates=...
type QueryDaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`        // 区间起点（含），YYYY-MM-DD
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`            // 区间终点（不含），YYYY-MM-DD
	Dates         []string               `protobuf:"bytes,3,rep,name=dates,proto3" json:"dates,omitempty"`        // 离散日期列表（自动去重升序，与区间并集）
	Detailed      bool                   `protobuf:"varint,4,opt,name=detailed,proto3" json:"detailed,omitempty"` // 默认 false（stats 粗粒度）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDaysRequest) Reset() {
	*x = QueryDaysRequest{}
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDaysRequest) ProtoMessage() {}

func (x *QueryDaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDaysRequest.ProtoReflect.Descriptor instead.
func (*QueryDaysRequest) Descriptor() ([]byte, []int) {
	return file_proto_goliday_v1_goliday_proto_rawDescGZIP(), []int{4}
}

func (x *QueryDaysRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *QueryDaysRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *QueryDaysRequest) GetDates() []string {
	if x != nil {
		return x.Dates
	}
	return nil
}

func (x *QueryDaysRequest) GetDetailed() bool {
	if x != nil {
		return x.Detailed
	}
	return false
}

type QueryDaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`   // "range"（仅区间）或 "list"（离散/混合）
	Start         string                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"` // 区间模式回显
	End           string                 `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	TotalDays     int32                  `protobuf:"varint,4,opt,name=total_days,json=totalDays,proto3" json:"total_days,omitempty"`
	Days          []*Day                 `protobuf:"bytes,5,rep,name=days,proto3" json:"days,omitempty"` // 恒为细粒度数值，升序
	Stats         *Stats                 `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDaysResponse) Reset() {
	*x = QueryDaysResponse{}
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDaysResponse) ProtoMessage() {}

func (x *QueryDaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDaysResponse.ProtoReflect.Descriptor instead.
func (*QueryDaysResponse) Descriptor() ([]byte, []int) {
	return file_proto_goliday_v1_goliday_proto_rawDescGZIP(), []int{5}
}

func (x *QueryDaysResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *QueryDaysResponse) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *QueryDaysResponse) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *QueryDaysResponse) GetTotalDays() int32 {
	if x != nil {
		return x.TotalDays
	}
	return 0
}

func (x *QueryDaysResponse) GetDays() []*Day {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *QueryDaysResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// 统计查询，对应 HTTP GET /api/v1/stats，入参同 QueryDaysRequest，不含 days 明细。
type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Start         string                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	TotalDays     int32                  `protobuf:"varint,4,opt,name=total_days,json=totalDays,proto3" json:"total_days,omitempty"`
	Stats         *Stats                 `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goliday_v1_goliday_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_goliday_v1_goliday_proto_rawDescGZIP(), []int{6}
}

func (x *StatsResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StatsResponse) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *StatsResponse) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *StatsResponse) GetTotalDays() int32 {
	if x != nil {
		return x.TotalDays
	}
	return 0
}

func (x *StatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_proto_goliday_v1_goliday_proto protoreflect.FileDescriptor

var file_proto_goliday_v1_goliday_proto_rawDesc = string([]byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x67, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x4c, 0x0a, 0x03,
	0x44, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x79, 0x70, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x79, 0x70, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0xc9, 0x01, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x64, 0x61, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x64, 0x61, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e,
	0x73, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x65, 0x6b, 0x65, 0x6e, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x65, 0x65, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x65, 0x73, 0x74, 0x69, 0x76, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x66, 0x65, 0x73, 0x74, 0x69, 0x76, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x64,
	0x6a, 0x75, 0x73, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x64,
	0x6a, 0x75, 0x73, 0x74, 0x65, 0x64, 0x22, 0x3f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x61, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44,
	0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x79, 0x70, 0x65, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x61, 0x79, 0x73,
	0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x67, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x22, 0x6c, 0x0a, 0x10, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x44, 0x61, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x22, 0xbc, 0x01, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x44, 0x61, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x44, 0x61, 0x79, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x79, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x79, 0x52, 0x04, 0x64, 0x61, 0x79, 0x73, 0x12, 0x27, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67,
	0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x22, 0x93, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x65, 0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x64, 0x61,
	0x79, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x44,
	0x61, 0x79, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x32, 0xe2, 0x01, 0x0a,
	0x0e, 0x47, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3f, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x44, 0x61, 0x79, 0x12, 0x19, 0x2e, 0x67, 0x6f, 0x6c, 0x69,
	0x64, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x48, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x79, 0x73, 0x12, 0x1c, 0x2e,
	0x67, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x44, 0x61, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x6f,
	0x6c, 0x69, 0x64, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61,
	0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6c, 0x69, 0x64,
	0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x79, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4a, 0x61, 0x79, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x74, 0x2f, 0x67, 0x6f, 0x6c, 0x69, 0x64,
	0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79,
	0x2f, 0x76, 0x31, 0x3b, 0x67, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_goliday_v1_goliday_proto_rawDescOnce sync.Once
	file_proto_goliday_v1_goliday_proto_rawDescData []byte
)

func file_proto_goliday_v1_goliday_proto_rawDescGZIP() []byte {
	file_proto_goliday_v1_goliday_proto_rawDescOnce.Do(func() {
		file_proto_goliday_v1_goliday_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_goliday_v1_goliday_proto_rawDesc), len(file_proto_goliday_v1_goliday_proto_rawDesc)))
	})
	return file_proto_goliday_v1_goliday_proto_rawDescData
}

var file_proto_goliday_v1_goliday_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_goliday_v1_goliday_proto_goTypes = []any{
	(*Day)(nil),               // 0: goliday.v1.Day
	(*Stats)(nil),             // 1: goliday.v1.Stats
	(*GetDayRequest)(nil),     // 2: goliday.v1.GetDayRequest
	(*GetDayResponse)(nil),    // 3: goliday.v1.GetDayResponse
	(*QueryDaysRequest)(nil),  // 4: goliday.v1.QueryDaysRequest
	(*QueryDaysResponse)(nil), // 5: goliday.v1.QueryDaysResponse
	(*StatsResponse)(nil),     // 6: goliday.v1.StatsResponse
}
var file_proto_goliday_v1_goliday_proto_depIdxs = []int32{
	1, // 0: goliday.v1.GetDayResponse.stats:type_name -> goliday.v1.Stats
	0, // 1: goliday.v1.QueryDaysResponse.days:type_name -> goliday.v1.Day
	1, // 2: goliday.v1.QueryDaysResponse.stats:type_name -> goliday.v1.Stats
	1, // 3: goliday.v1.StatsResponse.stats:type_name -> goliday.v1.Stats
	2, // 4: goliday.v1.GolidayService.GetDay:input_type -> goliday.v1.GetDayRequest
	4, // 5: goliday.v1.GolidayService.QueryDays:input_type -> goliday.v1.QueryDaysRequest
	4, // 6: goliday.v1.GolidayService.QueryStats:input_type -> goliday.v1.QueryDaysRequest
	3, // 7: goliday.v1.GolidayService.GetDay:output_type -> goliday.v1.GetDayResponse
	5, // 8: goliday.v1.GolidayService.QueryDays:output_type -> goliday.v1.QueryDaysResponse
	6, // 9: goliday.v1.GolidayService.QueryStats:output_type -> goliday.v1.StatsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_goliday_v1_goliday_proto_init() }
func file_proto_goliday_v1_goliday_proto_init() {
	if File_proto_goliday_v1_goliday_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_goliday_v1_goliday_proto_rawDesc), len(file_proto_goliday_v1_goliday_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_goliday_v1_goliday_proto_goTypes,
		DependencyIndexes: file_proto_goliday_v1_goliday_proto_depIdxs,
		MessageInfos:      file_proto_goliday_v1_goliday_proto_msgTypes,
	}.Build()
	File_proto_goliday_v1_goliday_proto = out.File
	file_proto_goliday_v1_goliday_proto_goTypes = nil
	file_proto_goliday_v1_goliday_proto_depIdxs = nil
}
