// goliday v1 API —— 节假日查询 gRPC 接口定义。
//
// 语义与 HTTP API 一致（见 docs/API.md）：
//   - 日期一律为 "YYYY-MM-DD" 字符串；
//   - 单日查询 detailed 切换粗/细粒度；多日明细 days 恒为细粒度数值；
//   - 区间为左闭右开 [start, end)，跨度上限 366 天；
//   - 离散列表自动去重并升序，与区间同时提供时取并集（mode=list）；
//   - 细粒度统计对组合日按标志位交叉计数（各键之和可大于 total_days）。
//
// 再生成（需 protoc 与两个插件在 PATH，在仓库根执行）：
//   protoc --go_out=. --go_opt=module=goliday \
//         --go-grpc_out=. --go-grpc_opt=module=goliday \
//         proto/goliday/v1/goliday.proto
// 参考版本：protoc v29.3、protoc-gen-go v1.36.5、protoc-gen-go-grpc v1.5.1。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/goliday/v1/goliday.proto

package golidayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GolidayService_GetDay_FullMethodName     = "/goliday.v1.GolidayService/GetDay"
	GolidayService_QueryDays_FullMethodName  = "/goliday.v1.GolidayService/QueryDays"
	GolidayService_QueryStats_FullMethodName = "/goliday.v1.GolidayService/QueryStats"
)

// GolidayServiceClient is the client API for GolidayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 节假日查询服务。参数错误统一返回 InvalidArgument，错误文案与 HTTP 一致。
type GolidayServiceClient interface {
	// 单日查询。
	GetDay(ctx context.Context, in *GetDayRequest, opts ...grpc.CallOption) (*GetDayResponse, error)
	// 区间/离散/混合查询（含逐日明细）。
	QueryDays(ctx context.Context, in *QueryDaysRequest, opts ...grpc.CallOption) (*QueryDaysResponse, error)
	// 统计查询（无逐日明细）。
	QueryStats(ctx context.Context, in *QueryDaysRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type golidayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGolidayServiceClient(cc grpc.ClientConnInterface) GolidayServiceClient {
	return &golidayServiceClient{cc}
}

func (c *golidayServiceClient) GetDay(ctx context.Context, in *GetDayRequest, opts ...grpc.CallOption) (*GetDayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDayResponse)
	err := c.cc.Invoke(ctx, GolidayService_GetDay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golidayServiceClient) QueryDays(ctx context.Context, in *QueryDaysRequest, opts ...grpc.CallOption) (*QueryDaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDaysResponse)
	err := c.cc.Invoke(ctx, GolidayService_QueryDays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golidayServiceClient) QueryStats(ctx context.Context, in *QueryDaysRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, GolidayService_QueryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GolidayServiceServer is the server API for GolidayService service.
// All implementations must embed UnimplementedGolidayServiceServer
// for forward compatibility.
//
// 节假日查询服务。参数错误统一返回 InvalidArgument，错误文案与 HTTP 一致。
type GolidayServiceServer interface {
	// 单日查询。
	GetDay(context.Context, *GetDayRequest) (*GetDayResponse, error)
	// 区间/离散/混合查询（含逐日明细）。
	QueryDays(context.Context, *QueryDaysRequest) (*QueryDaysResponse, error)
	// 统计查询（无逐日明细）。
	QueryStats(context.Context, *QueryDaysRequest) (*StatsResponse, error)
	mustEmbedUnimplementedGolidayServiceServer()
}

// UnimplementedGolidayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGolidayServiceServer struct{}

func (UnimplementedGolidayServiceServer) GetDay(context.Context, *GetDayRequest) (*GetDayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDay not implemented")
}
func (UnimplementedGolidayServiceServer) QueryDays(context.Context, *QueryDaysRequest) (*QueryDaysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDays not implemented")
}
func (UnimplementedGolidayServiceServer) QueryStats(context.Context, *QueryDaysRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryStats not implemented")
}
func (UnimplementedGolidayServiceServer) mustEmbedUnimplementedGolidayServiceServer() {}
func (UnimplementedGolidayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGolidayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GolidayServiceServer will
// result in compilation errors.
type UnsafeGolidayServiceServer interface {
	mustEmbedUnimplementedGolidayServiceServer()
}

func RegisterGolidayServiceServer(s grpc.ServiceRegistrar, srv GolidayServiceServer) {
	// If the following call pancis, it indicates UnimplementedGolidayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GolidayService_ServiceDesc, srv)
}

func _GolidayService_GetDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolidayServiceServer).GetDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GolidayService_GetDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolidayServiceServer).GetDay(ctx, req.(*GetDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolidayService_QueryDays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolidayServiceServer).QueryDays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GolidayService_QueryDays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolidayServiceServer).QueryDays(ctx, req.(*QueryDaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolidayService_QueryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolidayServiceServer).QueryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GolidayService_QueryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolidayServiceServer).QueryStats(ctx, req.(*QueryDaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GolidayService_ServiceDesc is the grpc.ServiceDesc for GolidayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GolidayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goliday.v1.GolidayService",
	HandlerType: (*GolidayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDay",
			Handler:    _GolidayService_GetDay_Handler,
		},
		{
			MethodName: "QueryDays",
			Handler:    _GolidayService_QueryDays_Handler,
		},
		{
			MethodName: "QueryStats",
			Handler:    _GolidayService_QueryStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/goliday/v1/goliday.proto",
}
